### ISSUE TITLE
Defeating the valkyrie queen crashes the game

### ISSUE THREAD

**Issue by sunsetbear** [matthewperiut/aether-fabric-b1.7.3#11]
when i defeated the valkyrie queen, the "saving chunks" with dirt background appeared and then my game closed.
the latest.log didn't say anything of note, but the console said the following:

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.bossName" is null
	at com.matthewperiut.aether.entity.living.EntityValkyrie.method_1368(EntityValkyrie.java:392)
	at net.minecraft.class_57.method_1346(class_57.java:817)
	at net.minecraft.class_57.method_1343(class_57.java:803)
	at net.modificationstation.stationapi.impl.world.FlattenedWorldManager.saveChunk(FlattenedWorldManager.java:64)
	at net.modificationstation.stationapi.impl.world.chunk.FlattenedWorldChunkLoader.method_812(FlattenedWorldChunkLoader.java:64)
	at net.minecraft.class_326.method_1050(class_326.java:127)
	at net.minecraft.class_326.method_1804(class_326.java:152)
	at net.minecraft.class_18.method_195(class_18.java:248)
	at net.minecraft.class_18.method_242(class_18.java:1608)
	at net.minecraft.client.Minecraft.method_2137(Minecraft.java:1498)
	at net.minecraft.client.Minecraft.run(Minecraft.java:754)
	at java.base/java.lang.Thread.run(Thread.java:833)
Shutting down culling task!
Stopping!

**Comment by sunsetbear** [comment]
Additionally, upon returning to the game, she is still alive, and suggests I "try defeating some weaker valkyries first" when i attack again. However, I can't actually leave the room, as it's locked...
I gave myself more medals with SPC and started to fight her again, revealing that her name actually is "null" lmao 
![image](https://github.com/matthewperiut/aether-fabric-b1.7.3/assets/8252642/811ea213-1c0d-4222-af92-4de0cd9f75a9)

**Comment by matthewperiut** [comment]
To fix leaving the room install BHCrestive and SPC, type /gamemode creative

In terms of the log actually that is very descriptive and I can fix it right when I get some free time to do it
